api:
  key: ${API_KEY}
  popularUrl: https://api.themoviedb.org/3/movie/popular
  genreUrl: https://api.themoviedb.org/3/genre/movie/list
  searchUrl: https://api.themoviedb.org/3/search/movie

auth:
  jwt:
    issuer: team.sparta.com
    secret: ${AUTH_JWT_SECRET}
    accessTokenExpirationHour: ${AUTH_JWT_ACCESSTOKENEXPIRATIONHOUR}
    refreshTokenExpirationHour: ${AUTH_JWT_REFRESHTOKENEXPIRATIONHOUR}


spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    jdbc:
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: postgres
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: embedded



  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
    springframework:
      security: debug
      web: debug

# Actuator
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  tomcat:
    mbeanregistry:
      enabled: true
  reactive:
    session:
      cookie:
        max-age: 120


oauth2:
  kakao:
    client_id: ${AUTH_KAKAO_ID}
    redirect_uri: "http://movie2gather.net/oauth-redirect-kakao"
  google:
    client_id: ${AUTH_GOOGLE_ID}
    redirect_uri: "http://movie2gather.net/oauth-redirect-google"
  naver:
    client_id: ${AUTH_NAVER_ID}
    redirect_uri: "http://movie2gather.net/oauth-redirect-naver"
