api:
  key: ${API_KEY}
  popularUrl: https://api.themoviedb.org/3/movie/popular
  genreUrl: https://api.themoviedb.org/3/genre/movie/list
  searchUrl: https://api.themoviedb.org/3/search/movie

auth:
  jwt:
    issuer: team.sparta.com
    secret: ${AUTH_JWT_SECRET}
    accessTokenExpirationHour: ${AUTH_JWT_ACCESSTOKENEXPIRATIONHOUR}

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${AUTH_GOOGLE_ID}
            client-secret: ${AUTH_GOOGLE_SECRET}
            scope:
              - email
              - profile

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
    springframework:
      security: debug

