api:
  key: ${API_KEY}
  popularUrl: https://api.themoviedb.org/3/movie/popular
  genreUrl: https://api.themoviedb.org/3/genre/movie/list
  searchUrl: https://api.themoviedb.org/3/search/movie

auth:
  jwt:
    issuer: team.sparta.com
    secret: ${AUTH_JWT_SECRET}
    accessTokenExpirationHour: ${AUTH_JWT_ACCESSTOKENEXPIRATIONHOUR}

spring:
  profiles: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    data:
      redis:
        host: ${REDIS_HOST}
        port: 6379
    jdbc:
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: postgres
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: embedded

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${AUTH_GOOGLE_ID}
            client-secret: ${AUTH_GOOGLE_SECRET}
            scope:
              - email
              - profile
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
    springframework:
      security: debug



