# workflow 이름
name: MovieToGather-Integration

# workflow 실행 조건
on:
  #  workflow_dispatch:
  pull_request:
    branches: [main, dev]

# workflow 가 저장소의 contents, PR 을 읽을 수 있도록
permissions:
  contents: read
  pull-requests: read


# 실행할 작업들
jobs:
  build-and-test:

    # 가상환경 운영체제OS 선택
    runs-on: ubuntu-latest

    steps:

      # PR 에 해당하는 레포지토리로 checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: application-test.yml 디렉토리 생성
        run: mkdir -p ./src/test/resources

      - name: application-test.yml 파일 생성
        run: touch ./src/test/resources/application-test.yml

      - name: application-test.yml 설정 추가
        run: echo -e "${{ secrets.APPLICATION_TEST_YML }}" > ./src/test/resources/application-test.yml

      # java JDK 설치
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Gradle 실행 권한 부여
      - name: Gradle 권한 부여
        run: chmod +x gradlew

      # 빌드, 테스트
      - name: Gradle 빌드
        run: ./gradlew build

      - name: 테스트
        run: ./gradlew test






